### ISSUE TITLE
edit model in the main profile 

### ISSUE THREAD

**Issue by SahanHerath** [SahanHerath/EventManagementSystem#49]
Edit the models in the main profile in a attrative manner .

**Comment by Anuka1995** [comment]
edited the decorator's profile model form

**Comment by Anuka1995** [comment]
edited the transporter's profile model form

**Comment by Anuka1995** [comment]
edited the photography and videography profile model form

**Comment by Anuka1995** [comment]
edited music and DJ profile model form

**Comment by Anuka1995** [comment]
edited dance profile model form

**Comment by Anuka1995** [comment]
edited poruwa decoration model form

**Comment by Anuka1995** [comment]
edited salon decoration model form

**Comment by Anuka1995** [comment]
edited catering user profile model form
