### ISSUE TITLE
finalization of hotel and hall profile

### ISSUE THREAD

**Issue by SahanHerath** [SahanHerath/EventManagementSystem#71]
hotel profile ,hall profile and both user views need to be finalized .for this you should
1. add a navigation bar to both views
2. package showing design in attractive way
3.hotel profile cover picture size
4.for all packages we are taking lot of data . so you may need to use a different pattern than other packages(for catering too)

**Comment by Anuka1995** [comment]
finalization part done without nav bar

**Comment by Anuka1995** [comment]
finalized with nav bar

**Comment by SahanHerath** [comment]
finalized
